/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmbank.gui;

import java.util.Calendar;
import java.util.Date;
import rmbank.database.BankDB;

/**
 *
 * @author Rolo
 */
public class CustomerInfo extends javax.swing.JPanel {

    private int customerid;

    /**
     * Creates new form NewJPanel
     */
    public CustomerInfo() {
        initComponents();
        this.customerid = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelabel = new javax.swing.JLabel();
        citylabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        namelabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        namelabel.setText("Name: -----");

        citylabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        citylabel.setText("City: -----");

        addresslabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addresslabel.setText("Address: -----");

        doblabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        doblabel.setText("Date of Birth: -----");

        deleteButton.setText("Delete Customer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(citylabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(addresslabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(doblabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(citylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addresslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doblabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (this.customerid >= 1) {
            try {
                new BankDB().deleteCustomer(this.customerid);
                
                Manage manage = Manage.getInstance();
                if (!manage.equals(null)) manage.loadCustomers();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    public void setID(int id) {
        this.customerid = id;
    }

    public void setName(String name) {
        namelabel.setText("Name: " + name);
    }

    public void setCity(String city) {
        citylabel.setText("City: " + city);
    }

    public void setAddress(String address) {
        addresslabel.setText("Address: " + address);
    }

    public void setDob(Date dob) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(dob);
        doblabel.setText("Date of Birth: " + cal.get(Calendar.DAY_OF_MONTH) + "/" + cal.get(Calendar.MONTH) + "/" + cal.get(Calendar.YEAR));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel citylabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel namelabel;
    // End of variables declaration//GEN-END:variables
}
