/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmbankatm;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Rolo
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    
    private long cardnum;
    private String pin;
    private State state;
    
    public MainGUI(long cardnum) throws Exception {
        if (BankDB.getInstance().isCardBlocked(cardnum)) System.exit(0);
        this.cardnum = cardnum;
        this.pin = "";
        this.state = State.PIN;
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action1 = new javax.swing.JButton();
        action2 = new javax.swing.JButton();
        action3 = new javax.swing.JButton();
        action4 = new javax.swing.JButton();
        action5 = new javax.swing.JButton();
        action6 = new javax.swing.JButton();
        action7 = new javax.swing.JButton();
        action8 = new javax.swing.JButton();
        KP_1 = new javax.swing.JButton();
        KP_2 = new javax.swing.JButton();
        KP_3 = new javax.swing.JButton();
        KP_4 = new javax.swing.JButton();
        KP_5 = new javax.swing.JButton();
        KP_6 = new javax.swing.JButton();
        KP_7 = new javax.swing.JButton();
        KP_8 = new javax.swing.JButton();
        KP_9 = new javax.swing.JButton();
        KP_0 = new javax.swing.JButton();
        KP_CANCEL = new javax.swing.JButton();
        KP_OK = new javax.swing.JButton();
        screenPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        action1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action1ActionPerformed(evt);
            }
        });

        action2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action2ActionPerformed(evt);
            }
        });

        action3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action3ActionPerformed(evt);
            }
        });

        action4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action4ActionPerformed(evt);
            }
        });

        action5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action5ActionPerformed(evt);
            }
        });

        action6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action6ActionPerformed(evt);
            }
        });

        action7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action7ActionPerformed(evt);
            }
        });

        action8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action8ActionPerformed(evt);
            }
        });

        KP_1.setText("1");
        KP_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_1ActionPerformed(evt);
            }
        });

        KP_2.setText("2");
        KP_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_2ActionPerformed(evt);
            }
        });

        KP_3.setText("3");
        KP_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_3ActionPerformed(evt);
            }
        });

        KP_4.setText("4");
        KP_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_4ActionPerformed(evt);
            }
        });

        KP_5.setText("5");
        KP_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_5ActionPerformed(evt);
            }
        });

        KP_6.setText("6");
        KP_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_6ActionPerformed(evt);
            }
        });

        KP_7.setText("7");
        KP_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_7ActionPerformed(evt);
            }
        });

        KP_8.setText("8");
        KP_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_8ActionPerformed(evt);
            }
        });

        KP_9.setText("9");
        KP_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_9ActionPerformed(evt);
            }
        });

        KP_0.setText("0");
        KP_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_0ActionPerformed(evt);
            }
        });

        KP_CANCEL.setText("C");
        KP_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_CANCELActionPerformed(evt);
            }
        });

        KP_OK.setText("OK");
        KP_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KP_OKActionPerformed(evt);
            }
        });

        screenPanel.setBackground(new java.awt.Color(87, 185, 242));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter PIN:");

        pinLabel.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        pinLabel.setForeground(new java.awt.Color(255, 255, 255));
        pinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screenPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(action8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KP_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KP_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KP_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KP_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KP_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KP_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KP_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KP_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KP_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KP_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(action5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(action1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(action4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KP_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KP_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KP_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KP_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void action1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action1ActionPerformed
        if (this.state != State.WITH) return;
        
        try {
            if (BankDB.getInstance().withdraw(cardnum, 10)) {
                JOptionPane.showMessageDialog(null, "Please, take your money", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to withdraw money", "", JOptionPane.ERROR_MESSAGE);    
            }
        } catch (Exception ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_action1ActionPerformed

    private void action2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action2ActionPerformed

    private void action3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action3ActionPerformed

    private void action4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action4ActionPerformed

    private void action5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action5ActionPerformed

    private void action6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action6ActionPerformed

    private void action7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_action7ActionPerformed

    private void action8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action8ActionPerformed
        if (this.state != State.WITH) return;
        
        try {
            String strMoney = JOptionPane.showInputDialog("How much money would you like to withdraw?");
            int money = (int)(Double.parseDouble(strMoney)-Double.parseDouble(strMoney)%1);
            
            if (BankDB.getInstance().withdraw(cardnum, money)) {
                JOptionPane.showMessageDialog(null, "Please, take your money", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to withdraw money", "", JOptionPane.ERROR_MESSAGE);    
            }
        } catch (Exception ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_action8ActionPerformed

    private void KP_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_1ActionPerformed
        addToPIN('1');
    }//GEN-LAST:event_KP_1ActionPerformed

    private void KP_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_2ActionPerformed
        addToPIN('2');
    }//GEN-LAST:event_KP_2ActionPerformed

    private void KP_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_3ActionPerformed
        addToPIN('3');
    }//GEN-LAST:event_KP_3ActionPerformed

    private void KP_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_4ActionPerformed
        addToPIN('4');
    }//GEN-LAST:event_KP_4ActionPerformed

    private void KP_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_5ActionPerformed
        addToPIN('5');
    }//GEN-LAST:event_KP_5ActionPerformed

    private void KP_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_6ActionPerformed
        addToPIN('6');
    }//GEN-LAST:event_KP_6ActionPerformed

    private void KP_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_7ActionPerformed
        addToPIN('7');
    }//GEN-LAST:event_KP_7ActionPerformed

    private void KP_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_8ActionPerformed
        addToPIN('8');
    }//GEN-LAST:event_KP_8ActionPerformed

    private void KP_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_9ActionPerformed
        addToPIN('9');
    }//GEN-LAST:event_KP_9ActionPerformed

    private void KP_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_0ActionPerformed
        addToPIN('0');
    }//GEN-LAST:event_KP_0ActionPerformed

    private void KP_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_CANCELActionPerformed
        if (this.state != State.PIN) return;
        
        this.pin = "";
        this.pinLabel.setText("");
    }//GEN-LAST:event_KP_CANCELActionPerformed

    private void KP_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KP_OKActionPerformed
        if (this.state != State.PIN) return;
        
        if (this.pin.length() < 4) return;
        try {           
            if (BankDB.getInstance().checkPin(cardnum, Integer.parseInt(pin))) {
                this.state = State.WITH;
                //this.getContentPane().remove(this.screenPanel);
                //int x = this.screenPanel.getX();
                //int y = this.screenPanel.getY();
                //this.screenPanel = new WithdrawPanel();
                //this.screenPanel.setLocation(x, y);
                //this.add(this.screenPanel);             
                //this.pack();
                
                this.pinLabel.setText("PIN Check Success");
                BankDB.getInstance().removeInvalidEntries(cardnum);
            } else {
                this.pinLabel.setText("PIN Check Failed");
                BankDB.getInstance().wrongPIN(cardnum);
                if (BankDB.getInstance().isCardBlocked(cardnum)) System.exit(0);
            }
        } catch (Exception ex) {ex.printStackTrace();}    
    }//GEN-LAST:event_KP_OKActionPerformed

    private void addToPIN(char c) {
        if (this.state != State.PIN) return;
        if (pin.length() >= 4) return;
        pin = pin + c;
        
        this.pinLabel.setText("");
        for (int i = 0; i < pin.length(); i++) {
            this.pinLabel.setText(this.pinLabel.getText()+'*');
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KP_0;
    private javax.swing.JButton KP_1;
    private javax.swing.JButton KP_2;
    private javax.swing.JButton KP_3;
    private javax.swing.JButton KP_4;
    private javax.swing.JButton KP_5;
    private javax.swing.JButton KP_6;
    private javax.swing.JButton KP_7;
    private javax.swing.JButton KP_8;
    private javax.swing.JButton KP_9;
    private javax.swing.JButton KP_CANCEL;
    private javax.swing.JButton KP_OK;
    private javax.swing.JButton action1;
    private javax.swing.JButton action2;
    private javax.swing.JButton action3;
    private javax.swing.JButton action4;
    private javax.swing.JButton action5;
    private javax.swing.JButton action6;
    private javax.swing.JButton action7;
    private javax.swing.JButton action8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JPanel screenPanel;
    // End of variables declaration//GEN-END:variables
}
